baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Sujith Quintelier'
theme = 'mytheme'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  [[params.socials]]
    name = "twitter"
    url = "https://x.com/SujithQ"
    icon = "bi bi-twitter-x"

  [[params.socials]]
    name = "facebook"
    url = "https://www.facebook.com/sujith.quintelier"
    icon = "bi bi-facebook"

  [[params.socials]]
    name = "github"
    url = "https://github.com/sujithq"
    icon = "bi bi-github"

  [[params.socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sujithquintelier/"
    icon = "bi bi-linkedin"

[services]
[services.disqus]
  shortname = 'sujithq'

[[menus.main]]
name = 'Blog'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Resume'
pageRef = '/resume'
weight = 20

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"