# baseURL = 'http://localhost:1313/'
# languageCode = 'en-us'
# title = 'Sujith Quintelier'
# theme = 'mytheme'

[params]
  dateFormat = "Jan 2, 2006"
  [params.gravatar]
    default = 'mp'
[[menus.main]]
  name = 'Blog'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Resume'
  pageRef = '/resume'
  weight = 20

[taxonomies]
  categories = "categories"
  tags = "tags"
  series = "series"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"